# Details of the database connection to use for running unit tests.
test:
  adapter: mysql
  encoding: utf8
  # Follow RCR standard for database name
  database: ept_invoicing_test
  host: localhost
  username: build
  password:
